<!--SLIDER-->
<div id="myCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for Slides -->
    <div class="carousel-inner">
        <div class="item active">
            <!-- Set the first background image using inline CSS below. -->
            <div class="fill" style="background-image:url('../public/images/slide3.png');"></div>
            <div class="carousel-caption">
                <div class="intro-message">
                    <h1>IT Courses</h1>
                    <h3>The first free educational resource</h3>
                    <hr class="intro-divider">
                    <ul class="list-inline intro-social-buttons">
                        <li>
                            <a href="#" class="btn btn-primary btn-lg btn-block"><i class="glyphicon glyphicon-eye-open glyphicon-fix"></i> <span class="button-name text-uppercase">View courses</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-primary btn-lg btn-block"><i class="glyphicon glyphicon-education glyphicon-fix"></i> <span class="button-name text-uppercase">Join us</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="item">
            <!-- Set the second background image using inline CSS below. -->
            <div class="fill" style="background-image:url('../public/images/slide2.png');"></div>
            <div class="carousel-caption">
                <div class="intro-message">
                    <h1>IT Courses</h1>
                    <h3>The first free educational resource</h3>
                    <hr class="intro-divider">
                    <ul class="list-inline intro-social-buttons">
                        <li>
                            <a href="#" class="btn btn-primary btn-lg btn-block"><i class="glyphicon glyphicon-eye-open glyphicon-fix"></i> <span class="button-name text-uppercase">View courses</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-primary btn-lg btn-block"><i class="glyphicon glyphicon-education glyphicon-fix"></i> <span class="button-name text-uppercase">Join us</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="item">
            <!-- Set the third background image using inline CSS below. -->
            <div class="fill" style="background-image:url('../public/images/slide1.png');"></div>
            <div class="carousel-caption">
                <div class="intro-message">
                    <h1>IT Courses</h1>
                    <h3>The first free educational resource</h3>
                    <hr class="intro-divider">
                    <ul class="list-inline intro-social-buttons">
                        <li>
                            <a href="#" class="btn btn-primary btn-lg btn-block"><i class="glyphicon glyphicon-eye-open glyphicon-fix"></i> <span class="button-name text-uppercase">View courses</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-primary btn-lg btn-block"><i class="glyphicon glyphicon-education glyphicon-fix"></i> <span class="button-name text-uppercase">Join us</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>
</div>
<!-- END SLIDER-->

<!--MISSION-->
<div class="content-section-b">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-10 col-md-offset-1">
                <div class="mission">
                    <h1 class="land-h">Mission</h1>
                    <p class="text-justify lead">
                        Lorem ipsum dапвапвапвolor sit amet, consectetur adipiscing elit.
                        Nulla quam velit, vulputate eu pharetra nec, mattis ac neque.
                        Duis vulputate commodo lectus, ac blandit elit tincidunt id.
                        Sed rhoncus, tortor sed eleifend tristique, tortor mauris molestie elit,
                        et lacinia ipsum quam nec dui. Quisque nec mauris sit amet elit
                        iaculis pretium sit amet quis magna. Aenean velit odio, elementum in tempus
                        Lorem ipsum dапвапвапвolor sit amet, consectetur adipiscing elit.
                        Nulla quam velit, vulputate eu pharetra nec, mattis ac neque.
                        Duis vulputate commodo lectus, ac blandit elit tincidunt id.
                        Sed rhoncus, tortor sed eleifend tristique, tortor mauris molestie elit,
                        et lacinia ipsum quam nec dui. Quisque nec mauris sit amet elit
                        iaculis pretium sit amet quis magna. Aenean velit odio, elementum in tempus
                    </p>

                </div>
            </div>
        </div>
    </div>
</div>
<!--END MISSION-->

<!--HOW ITS WORK-->
<div class="container-fluid">
    <h2 class="text-center land-h">How its work?</h2>
    <div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-md-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Simple way to learn:<br>something new</h2>
                    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                         aut cum deleniti ducimus error, ex fugiat aut cum deleniti ducimus error, ex fugiat
                        aut cum deleniti ducimus error, ex fugiat <a href="#">Ad, architecto asperiores</a>
                        aut cum deleniti ducimus error, ex fugiat.</p>
                </div>
                <div class="col-md-5 col-md-offset-2 col-sm-6">
                    <img class="img-responsive" src="../public/images/learn.jpg" alt="">
                </div>
            </div>

        </div>

    </div>

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-md-5 col-md-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Programming languages:<br>php, javascript, ruby</h2>
                    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        aut cum deleniti ducimus error, ex fugiat
                        <a href="#">Ad, architecto asperiores</a> aut cum deleniti ducimus error, ex fugiat.</p>
                </div>
                <div class="col-md-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="../public/images/programming.jpg" alt="">
                </div>
            </div>

        </div>

    </div>

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-md-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">You can share knowledge:<br>share you courses</h2>
                    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        aut cum deleniti ducimus error, ex fugiat aut cum deleniti ducimus error, ex fugiat
                        <a href="#">Ad, architecto asperiores</a> aut cum deleniti ducimus error, ex fugiat.
                        aut cum deleniti ducimus error, ex fugiataut cum deleniti ducimus error, ex fugiat
                    </p>
                </div>
                <div class="col-md-5 col-md-offset-2 col-sm-6">
                    <img class="img-responsive" src="../public/images/share.jpg" alt="">
                </div>
            </div>

        </div>

    </div>

</div>
<!--END HOW ITS WORK-->


<!--AUTHORS-->
<div class="content-section-b">
    <div class="container">
        <div class="row text-center">
            <h2 class="land-h">Authors</h2>
        </div>
        <div class="row text-center p-pad">
            <div class="col-md-2 col-md-offset-1">
                <img class="img-circle mini-pict" src="../public/images/author_house.jpg" alt="">
                <h3>Name Surname</h3>
                <p>PHP-developer</p>
            </div>
            <div class="col-md-2">
                <img class="img-circle mini-pict" src="../public/images/author_house.jpg" alt="">
                <h3>Name Surname</h3>
                <p>PHP-developer</p>
            </div>
            <div class="col-md-2">
                <img class="img-circle mini-pict" src="../public/images/author_house.jpg" alt="">
                <h3>Name Surname</h3>
                <p>PHP-developer</p>
            </div>
            <div class="col-md-2">
                <img class="img-circle mini-pict" src="../public/images/author_house.jpg" alt="">
                <h3>Name Surname</h3>
                <p>PHP-developer</p>
            </div>
            <div class="col-md-2">
                <img class="img-circle mini-pict" src="../public/images/author_house.jpg" alt="">
                <h3 class="test">Name Surname</h3>
                <p>PHP-developer</p>
            </div>
        </div>
    </div>
</div>
<!--END AUTHORS-->


