<div class="container">
    <div class="row">
        <div class=" col-md-4 col-md-offset-4">
            <?php
            if ((isset($_POST['username'])) && (isset($_POST['password']))) {
                echo '<div class="alert alert-danger" role="alert">Username or password is incorrect!</div>';
            }
            ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Login</strong>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" method="post" action="">
                        <div class="panel-body">
                            <div class="form-group input-group">
                                    <span class="input-group-addon"><span
                                            class="glyphicon glyphicon-envelope"></span></span>
                                <input class="form-control" type="email" name="email" placeholder="Email" required
                                       autofocus>
                            </div>
                            <div class="form-group input-group">
                                    <span class="input-group-addon"><span
                                            class="glyphicon glyphicon-lock"></span></span>
                                <input class="form-control" type="password" name="password" placeholder="Password"
                                       required>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Login</button>
                    </form>
                    <div class="forgot_password">
                        <a href="">Forgot your password?</a>
                    </div>
                </div>
                <div class="panel-footer">
                    <button type="submit" class="btn btn-success btn-block">Create account</button>
                </div>
            </div>
        </div>
    </div>
    <!-- end form -->
</div>