<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>IT Courses - Свободный образовательный проект</title>

    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link href="css/main.css" rel="stylesheet">
    <link href="css/half-slider.css" rel="stylesheet">


</head>

<body>
<!--TOP MENU-->
<header>
    <nav class="navbar navbar-default navbar-fixed-top top-menu-black">
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed burger-button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="#"><b>ITCourses</b></a>
                        </div>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="header_text_al">
                                    <a href="#">
                                        <span class="glyphicon glyphicon-comment"></span>
                                    </a>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" id="pad_null" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <span class="glyphicon glyphicon-user"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="#">My Courses</a>
                                        </li>
                                        <li>
                                            <a href="#">View Profile</a>
                                        </li>
                                        <li role="separator" class="divider"></li>
                                        <li>
                                            <a href="#">Log out</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>

                            <!--end header with foto-->
                            <form class="navbar-form" id="search" role="search">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search">
                                    <div class="input-group-btn">
                                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>
<!--END TOP MENU-->

<?= $this->content; ?>


<!--FOOTER-->
<footer id="footer" >
    <div class="container-fluid">
        <div class="navbar navbar-default">
            <div class="container col-md-12 text-center">
                <div class="row text-center">
                    <ul class="nav navbar-nav navbar-center footer-menu">
                        <li><a href="#">Courses</a></li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="#">About us</a></li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="#">Contacts</a></li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="#">Sitemap</a></li>
                    </ul>
                </div>
                <div class="row">
                    <p class="navbar-center copyright-mar">Copyright &copy; 2015 - Free education
                        <a href="#" >ITCourses.com</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>
<!--END FOOTER-->

<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<script src="js/jquery-1.11.3.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/slider.js"></script>

</body>
</html>